### ISSUE TITLE
入力値バリデーションってどこでやるのがいいんだろうね

### ISSUE THREAD

**Issue by mokoshin0720** [ispec-inc/starry#28]
現状uc層にバリューオブジェクトを渡しているということは、controller層でバリデーションもかけるべき、、？

懸念としては、
- controller層からdomain層を呼んでも良いのか（バリューオブジェクトを生成している時点で呼んでる説）
- バリューオブジェクトのバリデーションを行うためにDBのデータが必要な場合に複雑になりそう
    - 例えば、選択型の質問（A / B / C ）があった時に、入力で渡された値がDなのであればバリデーションで弾きたい、、、ただ、選択肢（A/ B/ C）がDBに入っている場合はcontrollerからDBを見に行かないといけなくなり、controllerが肥大化する

**Comment by mokoshin0720** [comment]
もしくは、uc層に渡す値はプリミティブ型にして全部uc層でやっちゃう方針が一番きれいだったり、、？
(controller層からdomain層を呼んでる問題もなくなりそう)

**Comment by yamad07** [comment]
> controller層からdomain層を呼んでも良いのか（バリューオブジェクトを生成している時点で呼んでる説）

これは俺も「いいのかな？」と疑心暗鬼になったけど、本家DDDでも呼んでいるし、特段懸念がなければよいのかな？と勝手に思ったり

**Comment by mokoshin0720** [comment]
解決！！！
