### ISSUE TITLE
hack, migrationをpackages以下に配置したい

### ISSUE THREAD

**Issue by YumaFuu** [ispec-inc/starry#31]
starryで扱うコード群(ディレクトリ)はpackages/に配置したい

**Comment by YumaFuu** [comment]
@yamad07 
hack, migrationもpackageに当たると思うのですが、いかがでしょう！

**Comment by yamad07** [comment]
このhackとmigrationは、starryのpackageをテストするために使うモノ、っていう位置付けです！！

**Comment by yamad07** [comment]
ちょっと意図を汲み取れきれる自信が全然ないのだけど、hackとmigrationはstarryを開発する上で必要なベースのスクリプトとか機能を提供するっていう意図でここに置いている

たとえばpackage内で複数のAPIがあった時に毎回マイグレーション書いたりdocker書くのめんどくさいので一元管理する、みたいなそんな意図です！

packageとして提供したい場合はpackageの中に作るのが良さそうで、ただstarry直下のこいつらはできれば残しておきたいかも？

**Comment by YumaFuu** [comment]
starryの開発用のディレクトリと提供されるpacakgeが同じになっちゃってるってことか

/devとか切ってとかできそうだな、ちょっといじってみる、ありがとう！
