### ISSUE TITLE
MySQL dockerのplatform指定を削除する

### ISSUE THREAD

**Issue by ninomae42** [ispec-inc/starry#34]
- MySQL5系までは、MySQL Dockerのarm版イメージが提供されていなかったが、MySQL8系以降のイメージではarm版イメージが提供されている
- Apple Silicon Macにおいて、linux/amd64のplatform指定をするとエミュレーションの処理が走るため、パフォーマンスがarmイメージと比較して悪い可能性があるため、platform指定を取り除きたい
- docker Engineは実行環境のplatformにおうじて、適切なimageをpullしてくるため、intel macでも問題なく動作する見込み

**Comment by yamad07** [comment]
@ninomae42 やりましょう！！お願いしても良いかな？

**Comment by ninomae42** [comment]
> @ninomae42 やりましょう！！お願いしても良いかな？

@yamad07 やります！
