### ISSUE TITLE
ADR ジェネレータBunをやめてDenoにする

### ISSUE THREAD

**Issue by YumaFuu** [ispec-inc/starry#37]
対象のコミット
https://github.com/ispec-inc/starry/commit/3e410c22865899529afd0e9f1e478911d2179668

以下の理由によりDenoがいいんじゃない？って思うので議論したい！
- 環境構築コストがほぼなくなる
- cliにdenoを採用している

**Comment by yamad07** [comment]
ランタイムだけ変えればサクッと対応できそうなやつか、じゃあ対応しましょう！

俺もちゃんと考えられてなかったんだけど、PHとかすでに導入されているPJに関してはbunで良いと思うが、starryにおいては統一されていた方が良いと思うので良さそう (@minminzemi どうかな？)

**Comment by yamad07** [comment]
@YumaFuu 別イシューになるけどCLIって今、普通に使えるんだっけ...？笑
(もし改善したい点とかあったらイシューあげてほしい！)

**Comment by minminzemi** [comment]
特に異論はないです！(denoよくわからないので今回の実装をどういう風に直して対応するのかよく分かってませんが)
