### ISSUE TITLE
Error 1305 (42000): SAVEPOINT tx_5 does not exist問題

### ISSUE THREAD

**Issue by satoshi0ta** [ispec-inc/starry#44]
基盤にOrion使っていて、トランザクションを貼っているユニットテストで並列にテストを実行すると、テストの基盤に使用している`txdb`の仕様上、↑のエラーになる

https://www.notion.so/ispec/Error-1305-42000-SAVEPOINT-tx_5-does-not-exist-14ea4f5c0f7e4b0ca9d392d1502e652c

**Comment by ninomae42** [comment]
トランザクションを使用するであろう、Update系のusecaseを追加して、そのユニットテスト内で複数のサブテストを回すようにしたらこの問題の再現ができそう

問題を回避する対応方針として
- トランザクションを使用しているusecaseのテストは並列実行を諦める
- テストの書き方を工夫して、並列実行を頑張る

↑の2つがあるけど、どちらを選択するかはOrionを利用する各PJで意思決定できたほうがよいと思うので、不具合の発生しない2パターンのテストケースの書き方を残しておくとよいかもと思ったので、手が空いたときにPRつくっておきます

**Comment by yamad07** [comment]
ありがとう！それがよさそう！！
